export const siteConfig = {
  name: "Javeed Ishaq - Product Engineer",
  authorName: "Javeed Ishaq",
  username: "javeedishaq",
  description:
    "Javeed Ishaq — Product Engineer specializing in Flutter, Next.js, NestJS, PostgreSQL, and Supabase. I build mobile and web products end-to-end — APIs, admin panels, authentication flows, and practical AI features like search, summaries, and retrieval.",
  url: "https://javeedishaq.com",
  links: {
    twitter: "https://x.com/javeedishaq",
    github: "https://github.com/javeedishaq",
    linkedin: "https://linkedin.com/in/javeedishaq",
    calendly: "https://calendly.com/javeedishaq",
  },
  ogImage:
    "https://res.cloudinary.com/dvt5vkfwz/image/upload/v1767384721/javeed_portfolio_og_image.png",
  iconIco: "/favicon.ico",
  logoIcon: "/favicon.ico",
  keywords: [
    "Javeed Ishaq",
    "Product Engineer",
    "Flutter Developer",
    "Dart Developer",
    "Next.js Developer",
    "React Developer",
    "TypeScript Developer",
    "NestJS Developer",
    "Node.js Developer",
    "Full Stack Developer",
    "Mobile App Developer",
    "Web Developer",
    "PostgreSQL",
    "Supabase",
    "AI Engineer",
    "AI Integration",
    "RAG",
    "pgvector",
    "OpenAI API",
    "BLOC",
    "Riverpod",
    "Clean Architecture",
    "REST APIs",
    "Authentication",
    "RBAC",
    "Software Engineer",
    "Tech Portfolio",
  ],
};
